### ISSUE TITLE
`-mono` option is missing

### ISSUE THREAD

**Issue by grzanka** [Tetrite/cBinder#78]
Documentation says that `-mono` option should be used. It is missing in the main.py file:

```
(cbinder) grzanka@grzanka-VirtualBox:~/PycharmProjects/cBinder$ git log --pretty=oneline -1
3ef6b39f441d1020f2c458bf6d8afe6875d2dff2 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #16 from Tetrite/doxygen_parser_prototype
(cbinder) grzanka@grzanka-VirtualBox:~/PycharmProjects/cBinder$ python main.py --help
usage: Generate python bindings [-h] -f path -d path [-i path] [-l lib_name]
                                [-b path] [-v]

optional arguments:
  -h, --help            show this help message and exit
  -f path, --files_path path
                        Path to C library
  -d path, --dest path  Path to destination directory
  -i path, --include path
                        Path to external library header files to be included
  -l lib_name, --library lib_name
                        Name of dynamic library to be linked with
  -b path, --lib_dir path
                        Path to directory with dynamic libraries
  -v, --verbose         Verbosity of output

```

**Comment by grzanka** [comment]
As suggested on slack I've updated the repo (git pull), now there are different problems (still following instruction from https://github.com/Tetrite/cBinder/blob/master/README.md):

```
(cbinder) grzanka@grzanka-VirtualBox:~/PycharmProjects/cBinder$ git log --pretty=oneline -1
ec1f08d28ea45641e4ac65780eea892f8a3bb8a1 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #79 from Tetrite/libamtrack_reference
(cbinder) grzanka@grzanka-VirtualBox:~/PycharmProjects/cBinder$ ls ../library/src/
AT_Algorithms_CPP.c  AT_DataMaterial.c   AT_Error.c                      AT_NumericalRoutines.c               AT_RDD.c                 AT_SPC.c                        AT_StoppingPowerDataICRU.c
AT_Algorithms_GSM.c  AT_DataParticle.c   AT_GammaResponse.c              AT_PhysicsRoutines.c                 AT_RDD_ExtendedTarget.c  AT_StoppingPower.c              AT_StoppingPowerDataPSTAR.c
AT_Algorithms_IGK.c  AT_DataRange.c      AT_Histograms.c                 AT_ProbabilityDistributions.c        AT_RDD_ShellAveraged.c   AT_StoppingPowerDataBethe.c     AT_SuccessiveConvolutions.c
AT.c                 AT_ElectronRange.c  AT_KatzModel.c                  AT_ProtonAnalyticalBeamParameters.c  AT_RDD_Simple.c          AT_StoppingPowerData.c          index.dox
AT_Constants.c       AT_EnergyLoss.c     AT_MultipleCoulombScattering.c  AT_ProtonAnalyticalModels.c          AT_RDD_Tabulated.c       AT_StoppingPowerDataFromFile.c  Makefile.am
(cbinder) grzanka@grzanka-VirtualBox:~/PycharmProjects/cBinder$ ls ../library/include/
AT_Algorithms_CPP.h  AT_DataParticle.h   AT_GammaResponse.h              AT_NumericalRoutines.h               AT_RDD_ExtendedTarget.h  AT_SPC.h                        AT_StoppingPowerDataPSTAR.h
AT_Algorithms_GSM.h  AT_DataRange.h      AT.h                            AT_PhysicsRoutines.h                 AT_RDD.h                 AT_StoppingPowerDataBethe.h     AT_StoppingPower.h
AT_Algorithms_IGK.h  AT_ElectronRange.h  AT_Histograms.h                 AT_ProbabilityDistributions.h        AT_RDD_ShellAveraged.h   AT_StoppingPowerDataFromFile.h  AT_SuccessiveConvolutions.h
AT_Constants.h       AT_EnergyLoss.h     AT_KatzModel.h                  AT_ProtonAnalyticalBeamParameters.h  AT_RDD_Simple.h          AT_StoppingPowerData.h
AT_DataMaterial.h    AT_Error.h          AT_MultipleCoulombScattering.h  AT_ProtonAnalyticalModels.h          AT_RDD_Tabulated.h       AT_StoppingPowerDataICRU.h
(cbinder) grzanka@grzanka-VirtualBox:~/PycharmProjects/cBinder$ head -n 5 tests/libamtrack/libamtrack_export_symbols_full.txt
AT_run_CPPSC_method
AT_run_CPPSS_method

AT_run_GSM_method
AT_GSM_local_dose_distrib
(cbinder) grzanka@grzanka-VirtualBox:~/PycharmProjects/cBinder$ ls /home/grzanka/tmp/gsl/include/
gsl
(cbinder) grzanka@grzanka-VirtualBox:~/PycharmProjects/cBinder$ rm -rf tmp/ && mkdir -p tmp/d
(cbinder) grzanka@grzanka-VirtualBox:~/PycharmProjects/cBinder$ PYTHONPATH=. python3 cBinder/main.py libamtrack -f ../library/src/ -f ../library/include/ -d tmp/d -es tests/libamtrack/libamtrack_export_symbols_full.txt -mono libAT compile -i /home/grzanka/tmp/gsl/include/ -b ../library/include/ -l gsl -l gslcblas -l m
[1407] WARN-enum: nameless enum ['enum', '{', 'TRPSPCBTAG_FILETYPE', '=', '1', ',', 'TRPSPCBTAG_FILEVERSION', '=', '2', ',', 'TRPSPCBTAG_FILEDATE', '=', '3', ',', 'TRPSPCBTAG_TARGNAME', '=', '4', ',', 'TRPSPCBTAG_PROJNAME', '=', '5', ',', 'TRPSPCBTAG_B', '=', '6', ',', 'TRPSPCBTAG_P', '=', '7', ',', 'TRPSPCBTAG_N', '=', '8', ',', 'TRPSPCBTAG_NZ', '=', '9', ',', 'TRPSPCDTAG_Z', '=', '10', ',', 'TRPSPCDTAG_N', '=', '11', ',', 'TRPSPCDTAG_NS', '=', '12', ',', 'TRPSPCDTAG_S', '=', '13', ',', 'TRPSPCDTAG_CUM', '=', '14', ',', 'TRPSPCDTAG_NC', '=', '15', ',', 'TRPSPCDTAG_NE', '=', '16', ',', 'TRPSPCDTAG_E', '=', '17', ',', 'TRPSPCDTAG_EREF', '=', '18', ',', 'TRPSPCDTAG_HISTO', '=', '19', ',', 'TRPSPCDTAG_RUNNINGSUM', '=', '20', ',', '}']
WARNING: Library not found: gslcblas
WARNING: Library not found: gsl
WARNING: Library not found: m
INFO: Assuming libs that were not found are system's
[1407] WARN-enum: nameless enum ['enum', '{', 'TRPSPCBTAG_FILETYPE', '=', '1', ',', 'TRPSPCBTAG_FILEVERSION', '=', '2', ',', 'TRPSPCBTAG_FILEDATE', '=', '3', ',', 'TRPSPCBTAG_TARGNAME', '=', '4', ',', 'TRPSPCBTAG_PROJNAME', '=', '5', ',', 'TRPSPCBTAG_B', '=', '6', ',', 'TRPSPCBTAG_P', '=', '7', ',', 'TRPSPCBTAG_N', '=', '8', ',', 'TRPSPCBTAG_NZ', '=', '9', ',', 'TRPSPCDTAG_Z', '=', '10', ',', 'TRPSPCDTAG_N', '=', '11', ',', 'TRPSPCDTAG_NS', '=', '12', ',', 'TRPSPCDTAG_S', '=', '13', ',', 'TRPSPCDTAG_CUM', '=', '14', ',', 'TRPSPCDTAG_NC', '=', '15', ',', 'TRPSPCDTAG_NE', '=', '16', ',', 'TRPSPCDTAG_E', '=', '17', ',', 'TRPSPCDTAG_EREF', '=', '18', ',', 'TRPSPCDTAG_HISTO', '=', '19', ',', 'TRPSPCDTAG_RUNNINGSUM', '=', '20', ',', '}']
[1407] WARN-enum: nameless enum ['enum', '{', 'TRPSPCBTAG_FILETYPE', '=', '1', ',', 'TRPSPCBTAG_FILEVERSION', '=', '2', ',', 'TRPSPCBTAG_FILEDATE', '=', '3', ',', 'TRPSPCBTAG_TARGNAME', '=', '4', ',', 'TRPSPCBTAG_PROJNAME', '=', '5', ',', 'TRPSPCBTAG_B', '=', '6', ',', 'TRPSPCBTAG_P', '=', '7', ',', 'TRPSPCBTAG_N', '=', '8', ',', 'TRPSPCBTAG_NZ', '=', '9', ',', 'TRPSPCDTAG_Z', '=', '10', ',', 'TRPSPCDTAG_N', '=', '11', ',', 'TRPSPCDTAG_NS', '=', '12', ',', 'TRPSPCDTAG_S', '=', '13', ',', 'TRPSPCDTAG_CUM', '=', '14', ',', 'TRPSPCDTAG_NC', '=', '15', ',', 'TRPSPCDTAG_NE', '=', '16', ',', 'TRPSPCDTAG_E', '=', '17', ',', 'TRPSPCDTAG_EREF', '=', '18', ',', 'TRPSPCDTAG_HISTO', '=', '19', ',', 'TRPSPCDTAG_RUNNINGSUM', '=', '20', ',', '}']
In file included from _libAT.c:494:
AT_EnergyLoss.h:244:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
  244 | double AT_lambda_Landau_Mode();
      | ^~~~~~
AT_EnergyLoss.h:246:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
  246 | double AT_lambda_Landau_FWHM_left();
      | ^~~~~~
AT_EnergyLoss.h:247:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
  247 | double AT_lambda_Landau_FWHM_right();
      | ^~~~~~
AT_EnergyLoss.h:248:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
  248 | double AT_lambda_Landau_FWHM();
      | ^~~~~~
AT_EnergyLoss.h:517:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
  517 | double AT_Gauss_Mode();
      | ^~~~~~
AT_EnergyLoss.h:518:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
  518 | double AT_Gauss_Mean();
      | ^~~~~~
AT_EnergyLoss.h:519:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
  519 | double AT_Gauss_FWHM();
      | ^~~~~~
/home/grzanka/PycharmProjects/library/src/AT_SuccessiveConvolutions.c:32:10: fatal error: AT_SuccessiveConvolutions.h: No such file or directory
   32 | #include "AT_SuccessiveConvolutions.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "/home/grzanka/.conda/envs/cbinder/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/grzanka/.conda/envs/cbinder/lib/python3.7/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/grzanka/.conda/envs/cbinder/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/grzanka/.conda/envs/cbinder/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/grzanka/.conda/envs/cbinder/lib/python3.7/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/grzanka/.conda/envs/cbinder/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/grzanka/.conda/envs/cbinder/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/grzanka/.conda/envs/cbinder/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/grzanka/.conda/envs/cbinder/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/grzanka/.conda/envs/cbinder/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/grzanka/.conda/envs/cbinder/lib/python3.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/grzanka/.conda/envs/cbinder/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cBinder/main.py", line 56, in <module>
    main()
  File "cBinder/main.py", line 52, in main
    BindingsGenerator(args).generate_bindings()
  File "/home/grzanka/PycharmProjects/cBinder/cBinder/cBinder/BindingsGenerator.py", line 81, in generate_bindings
    self._generate_bindings_monolith(monolith, headers, sources)
  File "/home/grzanka/PycharmProjects/cBinder/cBinder/cBinder/BindingsGenerator.py", line 215, in _generate_bindings_monolith
    ffibuilder.compile(verbose=verbosity)
  File "/home/grzanka/.conda/envs/cbinder/lib/python3.7/site-packages/cffi/api.py", line 723, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/grzanka/.conda/envs/cbinder/lib/python3.7/site-packages/cffi/recompiler.py", line 1527, in recompile
    compiler_verbose, debug)
  File "/home/grzanka/.conda/envs/cbinder/lib/python3.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/grzanka/.conda/envs/cbinder/lib/python3.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: CompileError: command 'gcc' failed with exit status 1
```

**Comment by certaindividual** [comment]
I would suggest changing the call. What was used (with added in bold):  
[...]  
libamtrack   
-f ../library/src/   
-f ../library/include/   
-d tmp/d   
-es tests/libamtrack/libamtrack_export_symbols_full.txt   
-mono libAT   
compile  
-i /home/grzanka/tmp/gsl/include/    <-- here is a path to gsl headers, which is indeed necessary  
**-i ../library/include/**  **<- adding libamtrack includes once again**
-b ../library/include/    **<- here should be a path not to libamtrack includes, but to folder which contains gsl '.so's, that is, libgsl.so and libgslcblas.so**
-l gsl   
-l gslcblas   
-l m

**Comment by grzanka** [comment]
Now it seems to work (reasonable size wheel generated) with following command:
```
PYTHONPATH=. python3 cBinder/main.py libamtrack -f ../library/src/ -f ../library/include/ -d tmp/d -es tests/libamtrack/libamtrack_export_symbols_full.txt -mono libAT compile -i /home/grzanka/tmp/gsl/include/ -i ../library/include/ -b /home/grzanka/tmp/gsl/lib/ -l gsl -l gslcblas -l m
```

but still some options (like `-f` and `-d`) are not explained when `--help` is added:
```
(cbinder) grzanka@grzanka-VirtualBox:~/PycharmProjects/cBinder$ PYTHONPATH=. python3 cBinder/main.py libamtrack -f ../library/src/ -f ../library/include/ -d tmp/d -es tests/libamtrack/libamtrack_export_symbols_full.txt -mono libAT compile -i /home/grzanka/tmp/gsl/include/ -i ../library/include/ -b /home/grzanka/tmp/gsl/lib/ -l gsl -l gslcblas -l m --help
usage: cBinder package_name compile [-h] [-i PATH] [-l NAME] [-b PATH]
                                    [-e ARGS]

optional arguments:
  -h, --help            show this help message and exit
  -i PATH, --include PATH
                        path to external library header files to be included
  -l NAME, --library NAME
                        name of dynamic library to be linked with
  -b PATH, --lib_dir PATH
                        path to directory with dynamic libraries
  -e ARGS, --extra_args ARGS
                        extra arguments passed to compiler
```

**Comment by Dwoosh** [comment]
that's probably because 'compile' command is used so help only shows arguments for compile mode

**Comment by certaindividual** [comment]
That's right. Analogously, command with shared mode will print help for shared subparser.
Command below prints main parser help:

` PYTHONPATH=. python3 cBinder/main.py --help`

```
usage: cBinder [-h] -f PATH -d PATH [-v] [-es EXPORT_SETTINGS]
               [-mono MONOLITH]
               package_name {compile,shared} ...

generate python bindings

required arguments:
  package_name          name of package
  -f PATH, --files_path PATH
                        path to C files
  -d PATH, --dest PATH  path to destination directory

optional arguments:
  -h, --help            show this help message and exit
  -v, --verbose         output verbosity
  -es EXPORT_SETTINGS, --export_settings EXPORT_SETTINGS
                        settings file with declarations to be wrapped
  -mono MONOLITH, --monolith MONOLITH
                        if this is specified then all sources are compiled
                        into one module

mode:
  {compile,shared}
    compile             compile all given source files
    shared              create bindings to dynamic/shared libraries (requires
                        header files too)

```

**Comment by Dwoosh** [comment]
Closing issue for now
